import "@/app/globals.css";
import BottomBar from "@/components/shared/BottomBar";
import RightSidebar from "@/components/shared/RightSidebar";
import TopBar from "../../components/shared/TopBar";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/components/theme-provider";
import LeftSideBarContainer from "@/components/containers/LeftSideBarContainer";
import { Toaster } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

import { Button } from "@/components/ui/button";
import {
  ArrowBigRight,
  ArrowBigRightIcon,
  CrossIcon,
  Minus,
  MinusCircle,
  MinusIcon,
} from "lucide-react";
import { RiAlignRight, RiCrossFill } from "react-icons/ri";
import {
  HiArrowCircleRight,
  HiArrowRight,
  HiChevronDoubleRight,
} from "react-icons/hi";
import { RxFileMinus } from "react-icons/rx";
import Link from "next/link";
import NotificationBar from "./NotificationBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}  `}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <NotificationBar></NotificationBar>
            {/* server-side component  */}
            <TopBar />
            <main className="bg-black mx-auto flex flex-row gap-2">
              {/* client-side component  */}
              <LeftSideBarContainer />
              <section className="mx-auto text-white w-[68%] p-2 overflow-y-scroll">
                <Toaster invert />
                {children}
              </section>

              {/* server-side-component  */}
              <RightSidebar />
            </main>

            {/* client-side component  */}
            <BottomBar />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
